from enum import Enum


class ExecutionStatus(str, Enum):
    COMPLETED = "COMPLETED"
    COMPILATION_ERROR = "COMPILATION_ERROR"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"
    SECURITY_VIOLATION = "SECURITY_VIOLATION"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class TestCaseStatus(str, Enum):
    __test__ = False
    PASSED = "PASSED"
    FAILED = "FAILED"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class SecurityStatus(str, Enum):
    SAFE = "SAFE"
    SECURITY_VIOLATION = "SECURITY_VIOLATION"
